<?php

return [
    'title'   => 'Pvtl/VoyagerFrontend',

    /*
    |--------------------------------------------------------------------------
    | Sitemap Configuration
    |--------------------------------------------------------------------------
    |
    | Sitemaps generated by spatie/laravel-sitemap package. Can be generated
    | with the 'voyager-frontend:generate-sitemap' command. The command
    | automatically schedueled to run every day at 13:15 by default,
    | but can be disabled by setting 'schedule' to false.
    |
    */
    'sitemap' => [
        'schedule' => true,
    ],

];
